### ISSUE TITLE
Foot escapes special chars with backslash when inserting a URL with Control+Shift+v

### ISSUE THREAD

**Issue by felixniemeyer** [r-c-f/foot#2]
Hey there, 

I use `yt-dlp` to download music from youtube. 
When I press Control+Shift+v to insert the copied URL, foot inserts backslashes in front of special chars. 

e.g. 
```
https://www.youtube.com/watch?v=bAtXMAPEpeY&t=3142s&pp=ygUKbmlnaHRoYXdrcw%3D%3D
```
becomes
```
https://www.youtube.com/watch\?v\=bAtXMAPEpeY\&t\=3142s\&pp\=ygUKbmlnaHRoYXdrcw%3D%3D
```
The command execution fails because I put single quotes around the pasted URL and because of the backslashes the URL is invalid. 

I noticed this only recently. 

I just tried copying and pasting just a portion of the URL like `com/watch?v=bAtXMAP` and it did not escape the `?` or `=`.

Can someone explain what's going on? And maybe instruct me how to deactivate this behavior. I searched the config file and man pages for `paste` and `escape` but couldn't find anything. 

I prefer to put an URL in single quotes manually instead of relying on magical escaping that occurs for certain text patterns :)

**Comment by r-c-f** [comment]
I do apologize, but I probably should have archived this some time ago -- this hasn't maintained in quite some time, as upstream foot has long since obviated the need for anything here.

**Comment by felixniemeyer** [comment]
Oh, thanks for your message. 
This repo is the first result when googling `foot terminal github` and it sounded quite official. 
I guess I'll head over to [codeberg](https://codeberg.org/dnkl/foot/issues) then and recreate this issue there. 
Thanks
